[project]
name = "training-llm-application-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "decorator==5.1.1",
    "faiss-cpu==1.10.0",
    "langchain-chroma==0.2.2",
    "langchain-cohere==0.4.2",
    "langchain-community==0.3.17",
    "langchain-core==0.3.35",
    "langchain-openai==0.3.6",
    "langchain-text-splitters==0.3.6",
    "langgraph==0.2.73",
    "nltk==3.9.1",
    "numpy==1.26.4",
    "openai==1.63.0",
    "pydantic-settings==2.7.1",
    "python-dotenv==1.0.1",
    "ragas==0.2.13",
    "rank-bm25==0.2.2",
    "rapidfuzz==3.11.0",
    "retry==0.9.2",
    "streamlit-feedback==0.1.4",
    "streamlit==1.42.0",
    "tavily-python==0.5.1",
]

[tool.uv]
dev-dependencies = ["jupyter==1.1.1"]
